In [ ]:
# 1. 배열 생성

import numpy as np

# 리스트로부터 배열 생성
arr = np.array([1, 2, 3, 4])
print(arr)
print(type(arr))

# 2차원 배열
mat = np.array([[1, 2], [3, 4]])
print(mat)


[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


In [ ]:
# 2. 배열 속성

print("shape:", arr.shape)   # (4,)
print("ndim:", arr.ndim)     # 차원 수
print("dtype:", arr.dtype)   # 데이터 타입
print("size:", arr.size)     # 전체 원소 개수


shape: (4,)
ndim: 1
dtype: int64
size: 4


In [ ]:
# 3. 초기화 함수

zeros = np.zeros((2, 3))         # 0으로 채운 배열
ones = np.ones((2, 3))           # 1로 채운 배열
arange = np.arange(0, 10, 2)     # 0, 2, 4, 6, 8
linspace = np.linspace(0, 1, 5)  # 0에서 1까지 균등 간격 5개

print(zeros)
print(ones)
print(arange)
print(linspace)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# 4. 배열 연산과 브로드캐스팅

a = np.array([1, 2, 3])
b = np.array([10, 10, 10])

print("a + b:", a + b)       # 원소별 덧셈
print("a * 2:", a * 2)       # 스칼라 곱(브로드캐스팅)


a + b: [11 12 13]
a * 2: [2 4 6]


In [ ]:
# 5. 슬라이싱과 불리언 인덱싱

arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])                # 20, 30, 40
print(arr[::2])                 # 짝수 인덱스
print(arr[arr > 25])            # 25 초과 값만


[20 30 40]
[10 30 50]
[30 40 50]


In [ ]:
# 응용 예시 — 나이와 혈압 데이터 분석

ages = np.array([25, 32, 47, 51])
bp = np.array([118, 130, 140, 125])

print("평균 나이:", ages.mean())
print("최대 혈압:", bp.max())
print("혈압 표준편차:", bp.std())

# 130 이상 혈압만 출력
print("고혈압:", bp[bp >= 130])


평균 나이: 38.75
최대 혈압: 140
혈압 표준편차: 8.011710179481033
고혈압: [130 140]


In [ ]:
# 응용 예시 — BMI 계산

heights = np.array([1.70, 1.65, 1.80, 1.75])  # m 단위
weights = np.array([65, 58, 90, 77])

bmi = weights / (heights ** 2)
print("BMI:", np.round(bmi, 1))

# 과체중(25 이상) 필터
print("과체중 BMI:", bmi[bmi >= 25])


BMI: [22.5 21.3 27.8 25.1]
과체중 BMI: [27.77777778 25.14285714]
