In [ ]:
import numpy as np

# 0차원 (스칼라)
scalar = np.array(42)
print("==== 0차원: 스칼라 ====")
print(f"값: {scalar}")
print(f"차원 수: {scalar.ndim}\n")

# 1차원 (벡터)
vector = np.array([1, 2, 3])
print("==== 1차원: 벡터 ====")
print(f"값: {vector}")
print(f"차원 수: {vector.ndim}\n")

# 2차원 (매트릭스)
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("==== 2차원: 매트릭스 ====")
print(f"값:\n{matrix}")
print(f"차원 수: {matrix.ndim}\n")

# 3차원 (텐서)
tensor_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print("==== 3차원: 텐서 ====")
print(f"값:\n{tensor_3d}")
print(f"차원 수: {tensor_3d.ndim}\n")

# 4차원 (텐서)
tensor_4d = np.array([
    tensor_3d,
    tensor_3d + 12
])
print("==== 4차원: 텐서 ====")
print(f"값:\n{tensor_4d}")
print(f"차원 수: {tensor_4d.ndim}\n")


==== 0차원: 스칼라 ====
값: 42
차원 수: 0

==== 1차원: 벡터 ====
값: [1 2 3]
차원 수: 1

==== 2차원: 매트릭스 ====
값:
[[1 2 3]
 [4 5 6]]
차원 수: 2

==== 3차원: 텐서 ====
값:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
차원 수: 3

==== 4차원: 텐서 ====
값:
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]]]]
차원 수: 4

